api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from api import views

app_name = 'api'

urlpatterns = [
    url(r'questions/$', views.QuestionList.as_view(), name='questions'),
    url(r'questions/(?P<pk>[0-9]+)/$', views.QuestionDetail.as_view(),
        name='question'),
    url(r'get_courses/$', views.CourseList.as_view(), name='get_courses'),
    url(r'start_quiz/(?P<course_id>[0-9]+)/(?P<quiz_id>[0-9]+)/$', views.StartQuiz.as_view(),
        name='start_quiz'),
    url(r'quizzes/$', views.QuizList.as_view(), name='quizzes'),
    url(r'quizzes/(?P<pk>[0-9]+)/$', views.QuizDetail.as_view(), name='quiz'),
    url(r'questionpapers/$', views.QuestionPaperList.as_view(),
        name='questionpapers'),
    url(r'questionpapers/(?P<pk>[0-9]+)/$',
        views.QuestionPaperDetail.as_view(), name='questionpaper'),
    url(r'answerpapers/$', views.AnswerPaperList.as_view(),
        name='answerpapers'),
    url(r'validate/(?P<answerpaper_id>[0-9]+)/(?P<question_id>[0-9]+)/$',
        views.AnswerValidator.as_view(), name='validators'),
    url(r'validate/(?P<uid>[0-9]+)/$',
        views.AnswerValidator.as_view(), name='validator'),
    url(r'course/(?P<pk>[0-9]+)/$',
        views.GetCourse.as_view(), name='get_course'),
    url(r'quit/(?P<answerpaper_id>\d+)/$', views.QuitQuiz.as_view(),
        name="quit_quiz"),
    url(r'login/$', views.login, name='login')
]

urlpatterns = format_suffix_patterns(urlpatterns)

grades/urls.py
from django.conf.urls import url
from grades import views

app_name = 'grades'

urlpatterns = [
    url(r'^$', views.grading_systems, name="grading_systems_home"),
    url(r'^grading_systems/$', views.grading_systems, name="grading_systems"),
    url(r'^add_grade/$', views.add_grading_system, name="add_grade"),
    url(r'^add_grade/(?P<system_id>\d+)/$', views.add_grading_system,
        name="edit_grade"),
]

online_test/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from online_test import views
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'online_test.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^exam/', include(('yaksh.urls', 'yaksh'))),
    url(r'^exam/reset/', include('django.contrib.auth.urls')),
    url(r'^', include('social_django.urls', namespace='social')),
    url(r'^grades/', include(('grades.urls', 'grades'))),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^stats/', include('stats.urls', namespace='stats')),
    url(r'^flatfiles/', include(('upload.urls', 'upload'))),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yaksh/urls.py
    url(r'^(?P<q_id>\d+)/check/$', views.check, name="check"),
    url(r'^get_result/(?P<uid>\d+)/(?P<course_id>\d+)/(?P<module_id>\d+)/$',
        views.get_result),
    url(r'^(?P<q_id>\d+)/check/(?P<attempt_num>\d+)/(?P<module_id>\d+)/'
        '(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',
        views.check, name="check"),
    url(r'^(?P<q_id>\d+)/skip/(?P<attempt_num>\d+)/(?P<module_id>\d+)/'
        '(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',
        views.skip, name="skip_question"),
    url(r'^(?P<q_id>\d+)/skip/(?P<next_q>\d+)/(?P<attempt_num>\d+)/'
        '(?P<module_id>\d+)/(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',
        views.skip, name="skip_question"),
    url(r'^enroll_request/(?P<course_id>\d+)/$', views.enroll_request,
        name='enroll_request'),
    url(r'^self_enroll/(?P<course_id>\d+)/$', views.self_enroll,
        name='self_enroll'),
    url(r'^view_answerpaper/(?P<questionpaper_id>\d+)/(?P<course_id>\d+)$',
        views.view_answerpaper, name='view_answerpaper'),
    url(r'^download/user_assignment/(?P<question_id>\d+)/(?P<user_id>\d+)/'
        '(?P<quiz_id>\d+)/(?P<course_id>\d+)$',
        views.download_assignment_file, name="download_user_assignment"),
    url(r'^show_lesson/(?P<lesson_id>\d+)/(?P<module_id>\d+)/'
        '(?P<course_id>\d+)/$', views.show_lesson, name='show_lesson'),
    url(r'^quizzes/view_module/(?P<module_id>\d+)/(?P<course_id>\d+)/$',
        views.view_module, name='view_module'),
    url(r'^next_unit/(?P<course_id>\d+)/(?P<module_id>\d+)/'
        '(?P<current_unit_id>\d+)/$', views.get_next_unit, name='next_unit'),
    url(r'^next_unit/(?P<course_id>\d+)/(?P<module_id>\d+)/$',
        views.get_next_unit, name='next_unit'),
    url(r'^next_unit/(?P<course_id>\d+)/(?P<module_id>\d+)/'
        '(?P<current_unit_id>\d+)/(?P<first_unit>\d+)/$',
        views.get_next_unit, name='next_unit'),
    url(r'^course_modules/(?P<course_id>\d+)/$',
        views.course_modules, name='course_modules'),
    url(r'^forum/course_forum/(?P<course_id>\d+)/$',
        views.course_forum,
        name='course_forum'),
    url(r'^forum/lessons_forum/(?P<course_id>\d+)/$',
        views.lessons_forum, name='lessons_forum'),
    url(r'^forum/(?P<course_id>\d+)/post/(?P<uuid>[0-9a-f-]+)/$',
        views.post_comments,
        name='post_comments'),
    url(r'^forum/(?P<course_id>\d+)/post/(?P<uuid>[0-9a-f-]+)/delete/',
        views.hide_post,
        name='hide_post'),
    url(r'^forum/(?P<course_id>\d+)/comment/(?P<uuid>[0-9a-f-]+)/delete/',
        views.hide_comment,
        name='hide_comment'),
    url(r'^manage/$', views.prof_manage, name='manage'),
    url(r'^manage/addquestion/$', views.add_question, name="add_question"),
    url(r'^manage/addquestion/(?P<question_id>\d+)/$', views.add_question,
        name="add_question"),
    url(r'^manage/add_exercise/(?P<course_id>\d+)/(?P<module_id>\d+)/$',
        views.add_exercise, name='add_exercise'),
    url(r'^manage/add_exercise/(?P<course_id>\d+)/(?P<module_id>\d+)/(?P<quiz_id>\d+)$',
        views.add_exercise, name='edit_exercise'),
    url(r'^manage/addquiz/(?P<course_id>\d+)/(?P<module_id>\d+)/$',
        views.add_quiz, name='add_quiz'),
    url(r'^manage/addquiz/(?P<course_id>\d+)/(?P<module_id>\d+)/(?P<quiz_id>\d+)$',
        views.add_quiz, name='edit_quiz'),
    url(r'^manage/gradeuser/$', views.grade_user, name="grade_user"),
    url(r'^manage/gradeuser/(?P<quiz_id>\d+)/(?P<course_id>\d+)/$',
        views.grade_user, name="grade_user"),
    url(r'^manage/gradeuser/(?P<quiz_id>\d+)/(?P<user_id>\d+)/'
        '(?P<course_id>\d+)/$',
        views.grade_user, name="grade_user"),
    url(r'^manage/gradeuser/(?P<quiz_id>\d+)/(?P<user_id>\d+)/'
        '(?P<attempt_number>\d+)/(?P<course_id>\d+)/$',
        views.grade_user, name="grade_user"),
    url(r'^manage/questions/$', views.show_all_questions,
        name="show_questions"),
    url(r'^manage/monitor/$', views.monitor, name="monitor"),
    url(r'^manage/monitor/(?P<quiz_id>\d+)/(?P<course_id>\d+)/$',
        views.monitor, name="monitor"),
    url(r'^manage/monitor/(?P<quiz_id>\d+)/(?P<course_id>\d+)/(?P<attempt_number>\d+)/$',
        views.monitor, name="monitor"),
    url(r'^manage/user_data/(?P<user_id>\d+)/(?P<questionpaper_id>\d+)/'
        '(?P<course_id>\d+)/$',
        views.user_data, name="user_data"),
    url(r'^manage/user_data/(?P<user_id>\d+)/$', views.user_data),
    url(r'^manage/designquestionpaper/(?P<course_id>\d+)/(?P<quiz_id>\d+)/'
        '(?P<questionpaper_id>\d+)/$',
        views.design_questionpaper, name='designquestionpaper'),
    url(r'^manage/designquestionpaper/(?P<course_id>\d+)/(?P<quiz_id>\d+)/$',
        views.design_questionpaper, name='designquestionpaper'),
    url(r'^manage/statistics/question/(?P<questionpaper_id>\d+)/'
        '(?P<course_id>\d+)/$',
        views.show_statistics, name="show_statistics"),
    url(r'^manage/statistics/question/(?P<questionpaper_id>\d+)/'
        '(?P<attempt_number>\d+)/(?P<course_id>\d+)/$',
        views.show_statistics, name="show_statistics"),
    url(r'^manage/download_quiz_csv/(?P<course_id>\d+)/(?P<quiz_id>\d+)/$',
        views.download_quiz_csv, name="download_quiz_csv"),
    url(r'^manage/duplicate_course/(?P<course_id>\d+)/$',
        views.duplicate_course, name='duplicate_course'),
    url(r'manage/courses/$', views.courses, name='courses'),
    url(r'manage/add_course/$', views.add_course, name='add_course'),
    url(r'manage/edit_course/(?P<course_id>\d+)$', views.add_course,
        name='edit_course'),
    url(r'manage/course_detail/(?P<course_id>\d+)/$', views.course_detail,
        name='course_detail'),

    url(r'manage/enroll/(?P<course_id>\d+)/$', views.enroll_reject_user,
        name="enroll_reject_user"),
    url(r'manage/enroll/(?P<course_id>\d+)/(?P<user_id>\d+)/$',
        views.enroll_user, name="enroll_user"),
    url(r'manage/reject/(?P<course_id>\d+)/(?P<user_id>\d+)/$',
        views.reject_user, name="reject_user"),
    url(r'manage/enrolled/reject/(?P<course_id>\d+)/(?P<user_id>\d+)/$',
        views.reject_user, {'was_enrolled': True},
        name="reject_enrolled_user"),
    url(r'manage/enrolled/reject/(?P<course_id>\d+)/$',
        views.enroll_reject_user, {'was_enrolled': True},
        name="reject_enrolled_users"),
    url(r'manage/enroll/rejected/(?P<course_id>\d+)/(?P<user_id>\d+)/$',
        views.enroll_user, {'was_rejected': True},
        name="enroll_rejected_user"),
    url(r'manage/enroll/rejected/(?P<course_id>\d+)/$',
        views.enroll_reject_user, {'was_rejected': True},
        name="enroll_rejected_users"),

    url(r'manage/upload_users/(?P<course_id>\d+)/$', views.upload_users,
        name="upload_users"),
    url(r'manage/send_mail/(?P<course_id>\d+)/$', views.send_mail,
        name="send_mail"),

    url(r'manage/toggle_status/(?P<course_id>\d+)/$',
        views.toggle_course_status, name="toggle_course_status"),
    url(r'^questions/filter$', views.questions_filter,
        name="questions_filter"),
    url(r'^editprofile/$', views.edit_profile, name='edit_profile'),
    url(r'^viewprofile/$', views.view_profile, name='view_profile'),
    url(r'^generate_qrcode/(?P<answerpaper_id>\d+)/(?P<question_id>\d+)/'
        r'(?P<module_id>\d+)/$',
        views.generate_qrcode, name='generate_qrcode'),
    url(r'^upload_file/(?P<key>.+)/$', views.upload_file, name='upload_file'),
    url(r'^manage/searchteacher/(?P<course_id>\d+)/$', views.search_teacher,
        name="search_teacher"),
    url(r'^manage/addteacher/(?P<course_id>\d+)/$', views.add_teacher,
        name='add_teacher'),
    url(r'^manage/remove_teachers/(?P<course_id>\d+)/$', views.remove_teachers,
        name='remove_teacher'),
    url(r'^manage/download_questions/$', views.show_all_questions,
        name="download_questions"),
    url(r'^manage/upload_questions/$', views.show_all_questions,
        name="upload_questions"),
    url(r'^manage/regrade/paper/question/(?P<course_id>\d+)/'
        '(?P<questionpaper_id>\d+)/(?P<question_id>\d+)/$',
        views.regrade, name='regrade_by_quiz'),
    url(r'^manage/regrade/user/(?P<course_id>\d+)/(?P<questionpaper_id>\d+)/'
        '(?P<answerpaper_id>\d+)/$', views.regrade, name='regrade_by_user'),
    url(r'^manage/regrade/user/question/(?P<course_id>\d+)/'
        '(?P<questionpaper_id>\d+)/(?P<answerpaper_id>\d+)/'
        '(?P<question_id>\d+)/', views.regrade, name='regrade_by_question'),
    url(r'^manage/(?P<mode>godmode|usermode)/(?P<quiz_id>\d+)/'
        '(?P<course_id>\d+)/$', views.test_quiz, name="test_quiz"),
    url(r'^manage/create_demo_course/$', views.create_demo_course,
        name="create_demo_course"),
    url(r'^manage/courses/download_course_csv/(?P<course_id>\d+)/$',
        views.download_course_csv, name="download_course_csv"),
    url(r'^manage/download/user_assignment/(?P<question_id>\d+)/'
        '(?P<user_id>\d+)/(?P<quiz_id>\d+)/(?P<course_id>\d+)$',
        views.download_assignment_file, name="download_user_assignment"),
    url(r'^manage/download/quiz_assignments/(?P<quiz_id>\d+)/'
        '(?P<course_id>\d+)$', views.download_assignment_file,
        name="download_quiz_assignment"),
    url(r'^manage/courses/download_yaml_template/',
        views.download_yaml_template, name="download_yaml_template"),
    url(r'^manage/download_sample_csv/',
        views.download_sample_csv, name="download_sample_csv"),
    url(r'^manage/courses/edit_lesson/(?P<course_id>\d+)/(?P<module_id>\d+)/$',
        views.edit_lesson, name="edit_lesson"),
    url(r'^manage/courses/edit_lesson/(?P<course_id>\d+)/(?P<module_id>\d+)/(?P<lesson_id>\d+)/$',
        views.edit_lesson, name="edit_lesson"),
    url(r'^manage/courses/designmodule/(?P<module_id>\d+)/$',
        views.design_module, name="design_module"),
    url(r'^manage/courses/designmodule/(?P<module_id>\d+)/'
        '(?P<course_id>\d+)/$', views.design_module, name="design_module"),

grades/forms.py
from grades.models import GradingSystem, GradeRange
from django import forms


class GradingSystemForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(GradingSystemForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': "form-control", 'placeholder': 'Grading Name'}
        )
        self.fields['description'].widget.attrs.update(
            {'class': "form-control",
             'placeholder': 'Grading description'}
        )
    class Meta:
        model = GradingSystem
        fields = ['name', 'description']


class GradeRangeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(GradeRangeForm, self).__init__(*args, **kwargs)
        self.fields['lower_limit'].widget.attrs.update(
            {'class': "form-control", 'placeholder': 'Lower limit'}
        )
        self.fields['upper_limit'].widget.attrs.update(
            {'class': "form-control", 'placeholder': 'Upper limit'}
        )
        self.fields['grade'].widget.attrs.update(
            {'class': "form-control", 'placeholder': 'Grade'}
        )
        self.fields['description'].widget.attrs.update(
            {'class': "form-control",
             'placeholder': 'Description'}
        )

    class Meta:
        model = GradeRange
        fields = "__all__"

grades/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from django.contrib import messages
from grades.forms import GradingSystemForm, GradeRangeForm
from grades.models import GradingSystem, GradeRange


@login_required
def grading_systems(request):
    user = request.user
    default_grading_system = GradingSystem.objects.get(name='default')
    grading_systems = GradingSystem.objects.filter(creator=user)
    return render(request, 'grading_systems.html', {'default_grading_system':
                  default_grading_system, 'grading_systems': grading_systems})


@login_required
def add_grading_system(request, system_id=None):
    user = request.user
    grading_system = None
    if system_id is not None:
        grading_system = GradingSystem.objects.get(id=system_id)
    GradeRangeFormSet = inlineformset_factory(GradingSystem, GradeRange,
                                              GradeRangeForm, extra=0)
    grade_form = GradingSystemForm(instance=grading_system)
    is_default = (grading_system is not None and
                  grading_system.name == 'default')

    if request.method == 'POST':
        formset = GradeRangeFormSet(request.POST, instance=grading_system)
        grade_form = GradingSystemForm(request.POST, instance=grading_system)
        if grade_form.is_valid():
            grading_system = grade_form.save(commit=False)
            grading_system.creator = user
            grading_system.save()
            system_id = grading_system.id
            if formset.is_valid():
                formset.save()
            messages.success(request, "Grading system saved successfully")
        if 'add' in request.POST:
            GradeRangeFormSet = inlineformset_factory(
                GradingSystem, GradeRange, GradeRangeForm, extra=1
                )
    formset = GradeRangeFormSet(instance=grading_system)

    return render(request, 'add_grades.html',
                  {'formset': formset,
                   'grade_form': grade_form, "system_id": system_id,
                   'is_default': is_default}
                  )

grades/templates/add_grades.html
{% extends "manage.html" %}
{% load static %}
{% load custom_filters %}
{% block title %} Add/Edit Grading {% endblock %}
{% block pagetitle %} Add/Edit Grading {% endblock %}
{% block script %}
    <script type="text/javascript" src="{% static 'yaksh/js/tinymce/js/tinymce/tinymce.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'yaksh/js/add_grades.js' %}"></script>
{% endblock %}
{% block content %}
<div class="container-fluid">
<div class="row">
    <div class="col-md-8">
        <ul class="nav nav-pills" id="course_tabs">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'yaksh:courses' %}">
                    My Courses
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'yaksh:add_course' %}">
                    Add/Edit Course
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'grades:grading_systems'%}" class="active nav-link" >
                    Add/View Grading Systems
                </a>
            </li>
        </ul>
    </div>
</div>
<hr>
<div class="container">
<a href="{% url 'grades:grading_systems'%}" class="btn btn-primary btn-lg">
    View Grading Systems
</a>
<br><br>
<div class="alert alert-info">
    Note: For grade range lower limit is inclusive and upper limit is exclusive
</div>
<br>
{% if messages %}
    {% for message in messages %}
      <div class="alert alert-dismissible alert-{{ message.tags }}">
          <button type="button" class="close" data-dismiss="alert">
              <i class="fa fa-close"></i>
          </button>
          <strong>{{ message }}</strong>
      </div>
    {% endfor %}
    <br>
{% endif %}
{% if not system_id  %}
    <form action="{% url 'grades:add_grade' %}" method="POST">
{% else %}
    <form action="{% url 'grades:edit_grade' system_id %}" method="POST">
{% endif %}
    {% csrf_token %}
    <table class="table table-responsive-sm">
        {% if grade_form.errors %}
            {% for field in grade_form %}
                {% for error in field.errors %}
                    <div class="alert alert-dismissible alert-danger">
                        <button type="button" class="close" data-dismiss="alert">
                            <i class="fa fa-close"></i>
                        </button>
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in grade_form.non_field_errors %}
                <div class="alert alert-dismissible alert-danger">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="fa fa-close"></i>
                    </button>
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        {% for field in grade_form %}
            {{ field }}
            <hr>
        {% endfor %}
        {{ formset.management_form }}
        <br>
        <div class="col">
            {% for form in formset %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                <b><u>Grade Range {{forloop.counter}}.</u></b>
                    <div class="row">
                    {% for field in form.visible_fields  %}
                      <div class="col-sm-3">
                        {% if field.field.widget|is_checkbox %}
                            {{ field.label_tag }}
                        {% endif %}
                        {{ field }}
                      </div>
                    {% endfor %}
                    </div>
            {% endfor %}
        </div>
    </table>
    {% if not is_default %}
        <input type="submit" id="add" name="add" value="Add/Delete Grade Range" class="btn btn-info btn-lg">
        <input type="submit" id="save" name="save" value="Save" class="btn btn-success btn-lg">
    {% else %}
        <div class="alert alert-warning">
            Note: This is a default grading system. You cannot change this.
        </div>
    {% endif %}
    <br><br>
</form>
</div>
</div>
{% endblock %}

grades/templates/grading_systems.html
{% extends "manage.html" %}
{% block title %} View Grading Systems {% endblock %}
{% block pagetitle %} View Grading Systems {% endblock %}
{% block content %}
<html>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <ul class="nav nav-pills" id="course_tabs">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'yaksh:courses' %}">
                        My Courses
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'yaksh:add_course' %}">
                        Add/Edit Course
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'grades:grading_systems'%}" class="active nav-link" >
                        Add/View Grading Systems
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <hr>
    <div class="container">
    <a href="{% url 'grades:add_grade' %}" class="btn btn-success btn-lg">
        <span class=" fa fa-plus-circle"></span>&nbsp;Add a Grading System
    </a>
    <br><br>
    <b> Available Grading Systems: </b>
    <table class="table">
        <tr>
            <th>Grading System</th>
            <th>Grading Ranges</th>
        </tr>
        <tr>
            <td>
            <a href="{% url 'grades:edit_grade' default_grading_system.id %}">
            {{ default_grading_system.name }}</a> (<b>Default Grading System</b>)
            </td>
            <td>
                <table class="table">
                    <tr>
                        <th>Lower Limit</th>
                        <th>Upper Limit</th>
                        <th>Grade</th>
                        <th>Description</th>
                    </tr>
                    {% for range in default_grading_system.graderange_set.all %}
                        <tr>
                            <td>{{range.lower_limit}}</td>
                            <td>{{range.upper_limit}}</td>
                            <td>{{range.grade}}</td>
                            {% if range.description %}
                                <td>{{range.description}}</td>
                            {% else %}
                                <td>------</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </table>
            </td>
        </tr>
        {% if grading_systems %}
        {% for system in grading_systems %}
            <tr>
            <td>
            <a href="{% url 'grades:edit_grade' system.id %}">{{ system.name }}</a>
            </td>
            <td>
                <table class="table">
                    <tr>
                        <th>Lower Limit</th>
                        <th>Upper Limit</th>
                        <th>Grade</th>
                        <th>Description</th>
                    </tr>
                    {% for range in system.graderange_set.all %}
                        <tr>
                            <td>{{range.lower_limit}}</td>
                            <td>{{range.upper_limit}}</td>
                            <td>{{range.grade}}</td>
                            {% if range.description %}
                                <td>{{range.description}}</td>
                            {% else %}
                                <td>------</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </table>
            </td>
            </tr>
        {% endfor %}
    </table>
    {% endif %}
    </div>
</div>
</html>
{% endblock %}